<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset=utf-8">

    <title>Fibonacci</title>

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <link href="bootstrap.css" rel="stylesheet">

</head>
<body id="LoginForm" class="text-center">

    <img src="error.jpeg"/>
    <h1>Something was wrong</h1>
    <h1>Enter correct value</h1><br/>

    <form action="/fibonacci" method="get">
        <button type="submit" class="btn btn-primary">Back home</button>
    </form>


</body>
</html>